# Site settings
title: firewalld
email: twoerner<AT>redhat.com
author: Thomas Woerner
lang: "en"

keywords: firewalld, firewall, linux, security, netfilter, dbus, daemon
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the firewalld project homepage!
  Firewalld provides a dynamically managed firewall with support for network/firewall zones that defines the trust level of network connections or interfaces.

baseurl:
url: "https://firewalld.org"

theme: just-the-docs

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


ga_tracking: UA-83693467-1
ga_tracking_anonymize_ip: true
logo: "images/firewalld.org.png"
search_enabled: true
enable_copy_code_button: true
nav_external_links:
  - title: Blog
    url: /blog
    hide_icon: true
    opens_in_new_tab: false
mermaid:
  version: "9.1.3"
aux_links:
  "FirewallD on GitHub":
    - "https://github.com/firewalld/firewalld"


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

plugins:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml
  
# Compress our Css
sass:
    style: :compressed

permalink: /:year/:month/:title
paginate: 5
paginate_path: "/blog/page/:num/"
